### ISSUE TITLE
书签删除的问题

### ISSUE THREAD

**Issue by Luffyying** [sunweiling/swl-bookmark#2]
coding girl请教一下，代码在本地运行，删除书签的时候遇到这样的问题：点击删除，没有什么反应，关闭书签，再次打开书签，发现已被删除。
如下代码，remove()执行完后，totalbookmarks的值没有变。remove函数是异步的吗？

               chrome.bookmarks.remove(String(id));
	       console.log('look here:');
               console.log(totalbookmarks);
	    	showMarks(totalbookmarks);

**Comment by sunweiling** [comment]
@Luffyying 可以试一下 showMarks 给它加一个定时器

**Comment by Luffyying** [comment]
主要是获得最新的totalbookmarks,可以这样：
chrome.bookmarks.remove(String(id),function(){
	    		chrome.bookmarks.getTree(function(bookmarks) {
		      		showMarks(bookmarks);
		      		totalbookmarks = bookmarks;
	    		});
	    	})

**Comment by sunweiling** [comment]
@Luffyying 嗯，有提供回调的方法的话是最好了
